"""One-off generator: converts Colormap.mat (+ MATLAB's built-in colormaps)
into a self-contained tools/colormaps.py, so the running app needs neither
scipy nor the .mat file. Re-run this only if you want to add/replace
colormaps; the app itself never calls it.

Usage:  python devtools/gen_colormaps.py /path/to/Colormap.mat
"""
import base64
import sys
import zlib

import numpy as np


def matlab_gray(n=256):
    r = np.linspace(0, 1, n)
    return np.stack([r, r, r], axis=1)


def matlab_jet(n=256):
    # MATLAB's jet: built from a 4-segment ramp, blue -> cyan -> yellow -> red
    x = np.linspace(0, 1, n)
    r = np.clip(np.minimum(4 * x - 1.5, -4 * x + 4.5), 0, 1)
    g = np.clip(np.minimum(4 * x - 0.5, -4 * x + 3.5), 0, 1)
    b = np.clip(np.minimum(4 * x + 0.5, -4 * x + 2.5), 0, 1)
    return np.stack([r, g, b], axis=1)


def matlab_hsv(n=256):
    h = np.linspace(0, 1, n, endpoint=False)
    i = np.floor(h * 6).astype(int) % 6
    f = h * 6 - np.floor(h * 6)
    p, q, t, v = 0.0, 1 - f, f, 1.0
    r = np.select([i == 0, i == 1, i == 2, i == 3, i == 4, i == 5],
                  [v, q, p, p, t, v]) * np.ones(n)
    g = np.select([i == 0, i == 1, i == 2, i == 3, i == 4, i == 5],
                  [t, v, v, q, p, p]) * np.ones(n)
    b = np.select([i == 0, i == 1, i == 2, i == 3, i == 4, i == 5],
                  [p, p, t, v, v, q]) * np.ones(n)
    return np.stack([r, g, b], axis=1)


def matlab_hot(n=256):
    x = np.linspace(0, 1, n)
    r = np.clip(x / 0.375, 0, 1)
    g = np.clip((x - 0.375) / 0.375, 0, 1)
    b = np.clip((x - 0.75) / 0.25, 0, 1)
    return np.stack([r, g, b], axis=1)


def matlab_copper(n=256):
    x = np.linspace(0, 1, n)
    return np.stack([np.clip(1.25 * x, 0, 1),
                     np.clip(0.7812 * x, 0, 1),
                     np.clip(0.4975 * x, 0, 1)], axis=1)


BUILTIN = {
    "gray": matlab_gray,
    "jet": matlab_jet,
    "hsv": matlab_hsv,
    "hot": matlab_hot,
    "copper": matlab_copper,
}


def main(mat_path):
    import scipy.io as sio
    maps = {}

    for name, fn in BUILTIN.items():
        maps[name] = (fn() * 255).round().astype(np.uint8)

    raw = sio.loadmat(mat_path)
    for key, value in raw.items():
        if key.startswith("__"):
            continue
        arr = np.asarray(value, dtype=float)
        # Colormap.mat holds (N,3) RGB tables in 0..1; anything else in the
        # file (e.g. the scalar 'cm_ring_area') is not a colormap -- skip it
        # rather than emitting a broken entry.
        if arr.ndim != 2 or arr.shape[1] != 3 or arr.shape[0] < 2:
            print(f"  skipping {key!r}: shape {arr.shape} is not an (N,3) colormap")
            continue
        if arr.min() < -1e-9 or arr.max() > 1 + 1e-9:
            print(f"  skipping {key!r}: values outside 0..1 (min={arr.min()}, max={arr.max()})")
            continue
        name = key[3:] if key.startswith("cm_") else key
        # 'copper' (and potentially others) exist both as a MATLAB builtin and
        # in the lab's Colormap.mat -- keep both rather than silently letting
        # one shadow the other, since they are genuinely different tables.
        if name in maps:
            name = f"{name}_lab"
        maps[name] = (arr * 255).round().astype(np.uint8)

    lines = [
        '"""',
        "tools/colormaps.py -- AUTO-GENERATED by devtools/gen_colormaps.py. Do not edit by hand.",
        "",
        "Colormap lookup tables for the .nxs viewer: MATLAB's built-in gray/jet/hsv/",
        "hot/copper plus every (N,3) table found in the lab's Colormap.mat. Stored as",
        "zlib-compressed base64 uint8 RGB so this module is self-contained -- the app",
        "needs neither scipy nor the original .mat file at runtime.",
        "",
        "Use get_lut(name, flip=False) to get an (N,3) uint8 array, or COLORMAP_NAMES",
        "for the ordered list of what's available.",
        '"""',
        "import base64",
        "import zlib",
        "",
        "import numpy as np",
        "",
        "_PACKED = {",
    ]
    for name, lut in maps.items():
        blob = base64.b64encode(zlib.compress(lut.tobytes(), 9)).decode("ascii")
        lines.append(f'    "{name}": ({lut.shape[0]}, "{blob}"),')
    lines.append("}")
    lines.append("")
    lines.append("# Ordered so the most commonly used ones come first in the GUI dropdown.")
    preferred = ["gray", "jet", "hsv", "hot", "copper"]
    rest = sorted(k for k in maps if k not in preferred)
    order = [k for k in preferred if k in maps] + rest
    lines.append(f"COLORMAP_NAMES = {order!r}")
    lines.append("")
    lines.append("_cache = {}")
    lines.append("")
    lines.append("")
    lines.append("def get_lut(name, flip=False):")
    lines.append('    """Return the (N,3) uint8 RGB lookup table for ``name``, reversed if')
    lines.append('    ``flip``. Raises KeyError with the list of valid names if unknown."""')
    lines.append("    if name not in _PACKED:")
    lines.append("        raise KeyError(f'Unknown colormap {name!r}; available: {COLORMAP_NAMES}')")
    lines.append("    if name not in _cache:")
    lines.append("        n, blob = _PACKED[name]")
    lines.append("        raw = zlib.decompress(base64.b64decode(blob))")
    lines.append("        _cache[name] = np.frombuffer(raw, dtype=np.uint8).reshape(n, 3)")
    lines.append("    lut = _cache[name]")
    lines.append("    return lut[::-1].copy() if flip else lut")
    lines.append("")

    out = "\n".join(lines)
    with open("tools/colormaps.py", "w", encoding="utf-8") as fh:
        fh.write(out)
    print(f"wrote tools/colormaps.py with {len(maps)} colormaps: {order}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/mnt/user-data/uploads/Colormap.mat")
